language: cpp
os: linux
services:
  - docker
compiler:
  - gcc
  - clang
env:
  - IMAGE=ubuntu:rolling
  - IMAGE=ubuntu:devel
before_install:
  - docker build -t img -f dockerfiles/$IMAGE/Dockerfile .
script:
  - docker run -e CC -e CXX img /bin/sh -c "autoreconf -i && ./configure && make"
